# ![Machine Learning Lab](banner.jpg)

# Laboratorio 6 Actividad

## Instrucciones generales

1. Esta actividad es de carácter individual. No se permite entregar la actividad después de la fecha establecida.
2. Al responder las preguntas de las actividades, por favor marquen las respuestas con la sección a la que corresponden, por ejemplo: `## Exploración de datos 2.1`. Es preferible que esto lo hagan con secciones de MarkDown.
3. Por favor asegurarse de que el notebook entregado tenga todas las celdas ejecutadas correctamente.
4. Por favor, nombren el archivo de acuerdo con el siguiente formato `{email}_lab6.ipynb`.
5. Si tienen alguna duda, pueden escribirme a mi correo `j.rayom@uniandes.edu.co` o contactarme directamente por Teams.

---

## Objetivos

1. Aplicar técnicas de clustering no supervisado utilizando distintos métodos como K-Means, Agglomerative Clustering y DBSCAN.
2. Explorar y preparar los datos mediante análisis exploratorio, normalización de variables y eliminación de columnas irrelevantes.
3. Evaluar y visualizar los resultados de clustering utilizando métricas como el coeficiente de silueta e interpretación visual de los clusters generados.

---

En esta ocasión trabajaremos con el dataset de World Happiness Report, el cual es una encuesta sobre la percepcion de felicidad a nivel mundial. Trabajaremos con los datos reportados para los años 2015, 2016, 2017, 2018, y 2019.

## Instrucciones

### 1. Descarga y exploración de datos (15%)

1. Descarga el dataset de World Happines Report desde Kaggle con el siguiente enlace:
   [Descargar Dataset](https://www.kaggle.com/datasets/unsdsn/world-happiness)
2. Carga todos los archivos csv y unirlos en un unico dataframe. Las columnas pueden tener distintos nombres, por esto se recomienda usar la función `standardize_columns` para normalizar los nombres de las columnas.

---

### 2. Preprocesamiento de Datos (20%)

1. Realizar un perfilamiento de los datos usando `ydata_profiling`
2. Elimina las columnas que tengan valores faltantes que sean identificadores o que no sean numéricas.
3. Normaliza todas las columnas.

---

### 3. Aplicación de algoritmos de clustering (65%)


1. **K-Means** (25%)
   - Realizar el gráfico de elbow, y determinar el mejor k
   - Aplica el algoritmo K-Means con k igual al resultado del paso anterior y visualiza los clusters usando un pairplot.

2. **Agglomerative Clustering** (20%)
   - Aplica el clustering jerárquico con `n_clusters=4` y visualiza los clusters en un pairplot.
   - Aplicar el algoritmo con `n_clusters=5` y encontrar que cluster del paso anterior fue separado.

3. **DBSCAN** (20%)
   - Aplica DBSCAN con `eps=0.2` y `min_samples=3`.
   - ¿Cuántos puntos fueron identificados como ruido (`-1`)?
   - Aplica DBSCAN con `eps=0.1` y `min_samples=3`.
     - ¿Cuántos puntos fueron identificados como ruido (`-1`)?

---

### 1. Descarga y exploración de datos

Carga del conjunto de datos **World Happiness Report** haciendo uso de los archivos disponibles para el periodo comprendido entre los años 2015 a 2019. Inicialmente se carga cada **.csv** como un DataFrame individual

In [1]:
import pandas as pd

In [2]:
wh_2015 = pd.read_csv("../datasets/2015.csv")
wh_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [3]:
wh_2016 = pd.read_csv("../datasets/2016.csv")
wh_2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [4]:
wh_2017 = pd.read_csv("../datasets/2017.csv")
wh_2017.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [5]:
wh_2018 = pd.read_csv("../datasets/2018.csv")
wh_2018.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [6]:
wh_2019 = pd.read_csv("../datasets/2019.csv")
wh_2019.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

Dado que cada **.csv** cuenta con nombres distintos para las mismas columnas, y que se desea trabajar con la totalidad de los datos comprendidos en el periodo mencionado anteriormente, se lleva a cabo una estandarización del nombre de las columnas o características

In [7]:
def standardize_columns(df):

    """Standardizes column names across different DataFrames."""

    col_map = {
        "Country": "country", "country": "country",
        "Happiness Rank": "happiness_rank", "Happiness.Rank": "happiness_rank", "Overall rank": "happiness_rank",
        "Happiness Score": "happiness_score", "Happiness.Score": "happiness_score", "Score": "happiness_score",
        "Economy (GDP per Capita)": "gdp_per_capita", "Economy..GDP.per.Capita.": "gdp_per_capita", "GDP per capita": "gdp_per_capita",
        "Family": "social_support", "Social support": "social_support",
        "Health (Life Expectancy)": "healthy_life_expectancy", "Health..Life.Expectancy.": "healthy_life_expectancy", "Healthy life expectancy": "healthy_life_expectancy",
        "Freedom": "freedom", "Freedom to make life choices": "freedom",
        "Trust (Government Corruption)": "perceptions_of_corruption", "Trust..Government.Corruption.": "perceptions_of_corruption", "Perceptions of corruption": "perceptions_of_corruption",
        "Generosity": "generosity",
        "Dystopia Residual": "dystopia_residual",
        "Standard Error": "standard_error",
        "Lower Confidence Interval": "lower_confidence_interval",
        "Upper Confidence Interval": "upper_confidence_interval",
        "Whisker.high": "upper_confidence_interval",
        "Whisker.low": "lower_confidence_interval",
        "year": "year"
    }

    df = df.rename(columns = lambda x: col_map.get(x, x))
      
    return df

In [8]:
wh_2015 = standardize_columns(wh_2015)
wh_2015.head()

,country,Region,happiness_rank,happiness_score,standard_error,gdp_per_capita,social_support,healthy_life_expectancy,freedom,perceptions_of_corruption,generosity,dystopia_residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [9]:
wh_2016 = standardize_columns(wh_2016)
wh_2016.head()

,country,Region,happiness_rank,happiness_score,lower_confidence_interval,upper_confidence_interval,gdp_per_capita,social_support,healthy_life_expectancy,freedom,perceptions_of_corruption,generosity,dystopia_residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [10]:
wh_2017 = standardize_columns(wh_2017)
wh_2017.head()

,country,happiness_rank,happiness_score,upper_confidence_interval,lower_confidence_interval,gdp_per_capita,social_support,healthy_life_expectancy,freedom,generosity,perceptions_of_corruption,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [11]:
wh_2018 = standardize_columns(wh_2018)
wh_2018.head()

,happiness_rank,Country or region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom,generosity,perceptions_of_corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [12]:
wh_2019 = standardize_columns(wh_2019)
wh_2019.head()

,happiness_rank,Country or region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom,generosity,perceptions_of_corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

Una vez estandarizados los nombres de las características o columnas compartidas entre los subconjuntos de datos, se unifican todos los datos en un solo DataFrame para facilitar su manejo y el entrenamiento de modelos de agrupación

In [13]:
world_happines_data = pd.concat([wh_2015, wh_2016, wh_2017, wh_2018, wh_2019])
world_happines_data.head()

,country,Region,happiness_rank,happiness_score,standard_error,gdp_per_capita,social_support,healthy_life_expectancy,freedom,perceptions_of_corruption,generosity,dystopia_residual,lower_confidence_interval,upper_confidence_interval,Dystopia.Residual,Country or region
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,NaN,NaN,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,NaN,NaN,NaN,NaN

In [14]:
print("ROWS = ", world_happines_data.shape[0])
print("COLUMNS = ", world_happines_data.shape[1])

ROWS =  782
COLUMNS =  16